### ISSUE TITLE
Dither lack of np

### ISSUE THREAD

**Issue by AceroMagico** [EllangoK/ComfyUI-post-processing-nodes#1]
numpy is not declared in Dither :

as it is:
import torch

class Dither:
    def __init__(self):
        pass

correct:
import torch
import numpy as np

class Dither:
    def __init__(self):
        pass

**Comment by EllangoK** [comment]
Thank you for letting me know! It should be fixed now in 28968fb25ce067e813af5b306235a61b2c9e043f.

I also added two more Nodes, Blend and FilmGrain. Let me know if you have any thoughts or suggestions.

**Comment by AceroMagico** [comment]
I saw, great, I like your suite.

Some suggestions:

Good to put the image of the workflow but for the convenience of those who want to use your suite also put a png with the workflow embedded so that you can drag and drop and test your nodes on the fly.

Don't create nodes that others have already created. Stay original as you did with the nodes like Dither Pixelize Glow FilmGrain KmeansQuantize Sharpen ColorCorrect.

**Comment by EllangoK** [comment]
Thank you! Yes I only discovered like WAS Suite yesterday, but there are barely any shared nodes with it and I'll keep it that way. I do need to add some duplicate basic stuff though like the canny node and blend nodes, just in case for users who don't have WAS Suite.

And thanks for the advice, I'll definetly add the work flow in as well.
