### ISSUE TITLE
Spam limit having default value None

### ISSUE THREAD

**Issue by huchenlei** [EllangoK/ComfyUI-post-processing-nodes#12]
https://github.com/EllangoK/ComfyUI-post-processing-nodes/blob/de7a29b339cd88586b54b171249b35785d20a23c/post_processing/pixel_sort.py#L16-L21

It will cause validation error in the new TS frontend's validation logic
![image](https://github.com/user-attachments/assets/4b28c0f7-fe96-4ea1-b61a-dc7275fb97df)

**Comment by EllangoK** [comment]
Fixed in 049eb2b4f3af7c3fc9f6f1f8c6565a02a43b087f
