### ISSUE TITLE
some function not work 

### ISSUE THREAD

**Issue by KumaPlayWithShader** [EllangoK/ComfyUI-post-processing-nodes#3]
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI_Portable\\ComfyUI\\custom_nodes\\ComfyUI-post-processing-nodes\\__init__.py'

Cannot import F:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI_Portable\\ComfyUI\\custom_nodes\\ComfyUI-post-processing-nodes\\__init__.py'

**Comment by EllangoK** [comment]
Thanks for letting me know, I pushed an update just now so if you git pull it, it should work. Let me know if you have any more issues.
