### ISSUE TITLE
Vignette effect bug

### ISSUE THREAD

**Issue by syllebra** [EllangoK/ComfyUI-post-processing-nodes#4]
Vignette effect is not working:

`Error occurred when executing Vignette:

Vignette.apply_vignette() got an unexpected keyword argument 'a'

File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
`

This is a typo where an old 'a' is still in parameters descriptions in stead of 'vignette', as is the parameter name in 'apply_vignette'.
fix: vignette.py line 13 "a" => "vignette"

Good job on these node btw!

**Comment by GalaxyTimeMachine** [comment]
I just hit this bug too. I tried making the change above, but still get the same error.

**Comment by GalaxyTimeMachine** [comment]
If I use the "Film Grain" node, which has a "vignette" option...that works!

**Comment by mickyboys** [comment]
Hi, vignette works via film grain. But overall, not very well. You can only set fixed numbers (1/2/3 not 0.4/1.3, etc.). That is a problem. A Vignette of 1 is already way too much. An idea how to solve this easily?

**Comment by digitaljohn** [comment]
@mickyboys I made a tweak, the behaviour may change slightly but allows granular control now. #6 

Unfortunately I have not managed to fix the Vignette only node, but IMO the single purpose nodes should be dropped as the Film Grain node is versatile enough.

**Comment by EllangoK** [comment]
Late 😓, but fixed now in 522817d3d39a68ffafa581f7656c4faa716cf236. Thanks for letting me know. I made Vignette match the change digitaljohn made to film grain.
