### ISSUE TITLE
The vignette within "Film Grain" node is too intense.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [EllangoK/ComfyUI-post-processing-nodes#5]
As per the title, even on the lowest setting of "1" it darkens the whole image.  Would it be possible for it to only affect the border (which is what the vignette should do) instead of the whole image? I'm looking to reproduce something like this, where the image is still bright in the middle, but with a darker frame to it:
![image](https://github.com/EllangoK/ComfyUI-post-processing-nodes/assets/52193044/4844ddba-7ca2-414f-9ce9-e020e1f0e23d)

These are comparison images using the node set to "0", "1" and then "10", and you can see how "1" just seems to spread across the whole image:
![0003_upscaled](https://github.com/EllangoK/ComfyUI-post-processing-nodes/assets/52193044/3ffac66d-22ba-4628-a6b5-cb4fa71ed283)
![0001_upscaled](https://github.com/EllangoK/ComfyUI-post-processing-nodes/assets/52193044/6c63ac93-f065-4764-906e-936d94530f37)
![0002_upscaled](https://github.com/EllangoK/ComfyUI-post-processing-nodes/assets/52193044/7a421226-e7b8-4a61-ac35-7a14a2b53b23)

**Comment by GalaxyTimeMachine** [comment]
I can work around the problem by adding the "ColorCorrect" node and tweaking the brightness. Not sure if this should still be addressed as it's not how a vignette should work...AFAIK.

**Comment by digitaljohn** [comment]
I made a tweak, the behaviour may change slightly but allows granular control now. #6

**Comment by EllangoK** [comment]
Merged digitaljohn's cr in, bit late but hopefully should be better now
